dist: xenial
language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.2"
install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    # Coverage unit test
    - coverage run -m unittest discover -s test/

after_success:
    - coveralls
